#include "parseTree.h"
#ifndef __PRINTTREE
#define __PRINTTREE 1


char *NodeNames[] = { "PROGRAM", "BLOCK", "NUMBER_CONSTANT", "CONSTANT", "VALUE", "EXPRESSION", "TERM", "COMPARATOR", "CONDITIONAL", "OUTPUT_LIST", "FOR_STATEMENT", "WHILE_STATEMENT", "FOR_EXPRESSIONS", "DO_STATEMENT", "IF_STATEMENT", "ASSIGNMENT_STATEMENT", "STATEMENT_LIST", "TYPENODE", "DECLARATION_BLOCK", "WRITE_STATEMENT", "READ_STATEMENT", "STATEMENT", "DECLARATION", "IDENTIFIERS_LIST", "INTEGER_NODE", "REAL_NODE", "IDENNODE" };

void PrintTree(TERNARY_TREE tree, int tabbing);

#endif
